### ISSUE TITLE
Give guidance on shared Inboxes

### ISSUE THREAD

**Issue by csarven** [csarven/ldn#6] opened 2016-06-24 15:11 UTC
Raised by @sandhawke

> > Multiple resources MAY use the same Inbox; one resource MAY have multiple Inbox URLs.
> 
> In this case, when I do a GET on a Resource's inbox, I may GET notifications from a million other Resource's inbox, and I wont be able to tell.  That seems awkward.

**Comment by csarven** [comment] 2016-07-06 19:01
@sandhawke A GET on the Inbox will only give references to the notifications, not the notifications themselves. The consumer decides if, what, or how much of that it wants to pursue. We can mention this in the spec along the lines of 'fetching of the notifications is at the discretion of the consumer'. See commit https://github.com/csarven/ldn/commit/7e3d8e76e38716dd0d35663ab6910b5d8375483d

Is this satisfactory? Otherwise, do you have a proposal?

**Comment by sandhawke** [comment] 2016-07-06 19:34
No, that doesn't address my point....

If two documents, D1 and D2, use the same inbox for their annotations, how can tell which of those notifications are about D1?

I suppose the answer is that I have to read them all, and inside each one look for it saying it's really about D1.   That means notifications SHOULD or MUST say what they're about, ...?

**Comment by csarven** [comment] 2016-07-06 20:40
What you are raising is still a subset of the problem _which of the notifications are useful to me_ - this is an arbitrary criteria and differs from one consumer to the next (even for the exact notification). Since a notification is not necessarily about 'x refers to y', there is nothing in particular to address here other than as you suggest; look inside the notification and then decide - I'm not sure (convinced) if that needs to be qualified with MUST/SHOULD. The notification describes itself based on 1) senders criteria / world-view / what it deems to be useful for consumers, and 2) receiver's constraints (if any), .. among other things.

Would something like this be satisfactory:

"If the consumer needs to determine whether a notification is of interest, then they MUST/SHOULD fetch the notification" -- I think this goes without saying, and I don't see how any constraint actually helps further. The Inbox is not going to say anything about the notification's contents so the only thing that's left to do is to look inside the notification.

**Comment by sandhawke** [comment] 2016-07-06 23:17
Yes, you're right.    Probably what would help would be use cases or examples in the spec, so the reader can have some indication you've thought this through.   

Like, why would you ever want to mix it all together?

On the other part, if there are multiple endpoints, do I send the ALL of them or ANY of them, and to get everything, do I need to read ANY of them or ALL of them?   You probably want ALL/ANY or ANY/ALL.    ALL/ALL is redundant and ANY/ANY means all the endpoints need to synchronize.

**Comment by sandhawke** [comment] 2016-07-06 23:20
Send to ANY and read ALL is probably the best bet, because the failure mode is a temporary and detectable data loss instead of a permanent and undetectable data loss.

**Comment by csarven** [comment] 2016-07-07 04:05
Reconsidering "multiple resources MAY use the same Inbox": I would rather omit that statement altogether. Surely an Inbox can be reused by different resources, and the use cases would vary e.g., grouping or categorisation; an Inbox that receives reminders from different events, replies to the abstracts of all my articles, or and Inbox to catch activity on all of my assets. Certainly other reasons that would escape us right now in this thread.

At first it seems like the statement adds useful information but perhaps only complicates things further by having to explain what the consumer should do with it. Well, the author/publisher probably knows that best because they are the ones assigning the Inboxes to the resources. Presumably the author/publisher is taking on that task with the mindset that's best for _their_ consumers.

This is more or less addressed in the _[summary of the consumer](https://rawgit.com/csarven/ldn/master/index.html#summary-consumer)_:

> Retrieves the contents of the Inbox URL with a GET request, and uses according to the needs of application.

Again, right now I have a preference to omit this information. The MAY was introduced to hint at the idea of what's possible. People can probably come to the same conclusion without it being explicitly mentioned. If including or not including that information poses a particular error-handling that should be specified, I think that'd be worthwhile to pursue.

What do you think? Does this address your original issue?

**Comment by csarven** [comment] 2016-07-07 04:08
As for multiple inboxes, the spec currently says this about [sending](https://rawgit.com/csarven/ldn/master/index.html#sending):

> If multiple Inboxes are discovered, senders MUST de-duplicate Inbox URLs and send to _all unique_ Inbox URLs.

If you have concerns about that, I think a separate issue would be appropriate.

**Comment by sandhawke** [comment] 2016-07-07 12:32
Interesting thought about leaving out the mention.   If you left it out, my first assumption would be that resources would each have their own inbox.   Now the question is, how much trouble would that assumption get me into?

As a producer or consumer of annotations, I would probably assume all the annotations in D1's inbox were about D1.   I might write my code with that assumption, and when I discovered a document that shared its inbox with another, my code my break.  And I'd start by assuming the documents were broken, and we'd argue about what the spec meant, and then eventually I'd blame the spec for being ambiguous about this.

So, I suggest best to keep the MAY,  and just use a list like you included here...

> e.g., grouping or categorisation; an Inbox that receives reminders from different events, replies to the abstracts of all my articles, or and Inbox to catch activity on all of my assets. 

to help people be clear in their heads how these things are supposed to work.   If you don't tell them, they'll make their own problematic assumptions, like the example me three paragraphs ago.

**Comment by csarven** [comment] 2016-07-07 13:49
"I might write my code with that assumption, and when I discovered a document that shared its inbox with another, my code my break." -- break how? Again, the sender is compiling the payload, and the consumer's code is always subject to "break" regardless of other resources using the same Inbox or not. For your code not to "break" in any circumstance (and this is a stretch), the consumer will have to create a deterministic payload for any resource and for all constraints imposed by the Inbox. A more likely case is that, the consumer puts information like 'this resource has these type of relations with the resource over there' (for the annotation case you've provided). For your code not to "break", when you look at that resource, you'll see whether any of the statements match your criteria e.g., is it pointing at the resource that I'm interested in? is it licensed with something that I'm okay to use? is the type of relation between the resources something I recognise or use? is it authored by someone I like? The point is, the annotation (or more specifically, x has an explicit relation y) is one use-case. I don't think we can generalise based off that.

This is not about the ambiguity in the spec but rather the original agreement between the receiver (publisher) and the sender for the payload can be put to use by potential consumers. However they've determined that is out of scope in my opinion.

I still prefer to leave this information out, but I can live with it. Created https://github.com/csarven/ldn/commit/bc739bc5c5476f0a0b457c45d05ca6f27b67fde4 . Is this satisfactory to close this issue? Thanks.

I'd like @rhiaro to give a pass at this issue and see the spec reads now - needs editing or truncating example / use-cases would be nice.

**Comment by sandhawke** [comment] 2016-07-07 13:57
So, your point is that consumers should make essentially no assumptions about notifications.   Just, here are some bytes+content-types, provided by third parties, which you might find useful, somehow related to this resource.

A better name for this might be a bulletin board service...

**Comment by sandhawke** [comment] 2016-07-07 14:02
In answer to "break how?", well, my simple tool would end up showing all annotations on all documents using that inbox as if annotations on D1.    You visit D1 and you see comments that aren't actually about D1!

**Comment by csarven** [comment] 2016-07-07 14:04
That's what the `constrainedBy` information is for. It is so that if the receiver chooses to give instructions on what the payload should contain, it'll be there for the sender to comply with. It helps the consumer to also check whether it can utilise any of the the notifications with such graph pattern. This is _pay as you go_ in the sense that it is possible to address some of your concerns, but no one is forced to.. and if of course the receiver/publisher of the data assigns the same Inbox for different resources (for _whatever_ reason - with the assumption that they know their data and consumers best).

[It'd be great to relive the BBS era, but some say that the Web is slightly more convenient nowadays.]

**Comment by csarven** [comment] 2016-07-07 14:06
If you are designing your tool to display all annotations without checking whether the information fits your interest, that's your call. That's a perfectly fine thing to do and that's not "breaking". That's just a design decision to display all and whatever. We can equally say that others will design a tool that will check for a pattern that's usable to them.

**Comment by sandhawke** [comment] 2016-07-07 14:39
Yes, it absolutely is "breaking".    In this scenerio, I only intended to display annotations about D1, but I somehow ended up displaying annotations about D2.   From my perspective,  my software did something I didn't expect and that my users didn't expect.  They report a bug.  It is a bug.   It's caused by your spec ending up giving me the wrong impression of how the protocol works.    You can say that's my fault, I should have understood what the spec meant.   I would disagree - given someone raised issue 6 a long time ago, showing people could easily be misled.   If you know there's ambiguity and you choose to leave it unresolved, it becomes your fault.

All that is in defence of keeping some explanation text in there.   Your suggested patch      https://github.com/csarven/ldn/commit/bc739bc5c5476f0a0b457c45d05ca6f27b67fde4 is fine for this issue, so go ahead and close it, and mark it Commenter Satisfied.     (if you're not using https://github.com/sandhawke/spec-labels-min you should :-)

**Comment by csarven** [comment] 2016-07-07 15:40
For the purpose of this discussion / documentation, how about we go with "potentially breaking": if the receiver doesn't take the necessary steps to organise/manage/constraining the Inbox meanwhile setting multiple resources to use the same Inbox, and senders not providing sufficient information that'd be useful or leading to critical issues for consumers, and consumers not filtering anything and processing everything. I can see that happening. I'm only pointing out that all actors are involved here for the scenario you describe to occur. Perhaps the degree of potential breakage / chaos / armageddon is something we don't completely agree on, but most importantly we agree on the explanation text :) Thanks for raising this issue/concern!

@rhiaro please review/update. Close. Label. Sandro's spec-labels-min are in place.

**Comment by csarven** [comment] 2016-07-07 15:55
Just a heads up: sections https://rawgit.com/csarven/ldn/master/index.html#constraints and https://rawgit.com/csarven/ldn/master/index.html#payload-verification I think gives some guidance on minimising these types of potential issues.

**Closed as completed** 2016-07-08 14:29 UTC
Labels: Commenter Satisfied
